import Head from "next/head";
import Form from "../components/Form";
import Table from "../components/Table";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useState } from "react";

export default function Home() {
  const [visible, setVisible] = useState(false);

  //toggle visible method
  const handleAdd = () => {
    setVisible(visible ? false : true);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-xl text-center">Employee Management</h1>

        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={handleAdd}
              className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-gray-800"
            >
              Add Employee <span className="px-1"></span>
            </button>
          </div>

          {/* collapsable form */}

          {/* table */}
        </div>
        <div className="container mx-auto py-5">
          {visible ? <Form></Form> : <></>}
        </div>

        <div className="container mx-auto">
          <Table></Table>
        </div>
        <ToastContainer />
      </main>
    </>
  );
}
